### ISSUE TITLE
KeyValueType should be Record<string, any> instead of Record<string, string>

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#102]
https://github.com/dapr/js-sdk/blob/8bfda5b1e6ea46a8ca02ac22481e3ffec0dde4bd/src/types/KeyValue.type.ts

should be changed to string, any instead of string, string

**Comment by dolencd** [comment]
Would it make more sense to use the `unknown` type for this? https://devblogs.microsoft.com/typescript/announcing-typescript-3-0-rc-2/#the-unknown-type
