### ISSUE TITLE
Crash when setting state in the form of a plain JS Object when using gRPC

### ISSUE THREAD

**Issue by dolencd** [dapr/js-sdk#125]
## Expected Behavior

When using state.set with gRPC it should be able to store a plain object by internally using JSON.stringify.

## Actual Behavior

The library crashes with a TypeError because it attempts to create a Buffer from a JS Object (because it didn't call JSON.stringify).

## Steps to Reproduce the Problem
The following code will crash:
```
await client.state.save("state-redis", [
                {
                    key: "key-4",
                    value: {
                        nested: {
                            str: "string",
                            num: 123
                        }
                    }
                }
            ]);
```

**Comment by XavierGeerinck** [comment]
Closing as this is resolved
