### ISSUE TITLE
Feature: Configuration API

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#140]
## Describe the proposal

https://docs.dapr.io/developing-applications/building-blocks/configuration/

Will also close #258

**Comment by XavierGeerinck** [comment]
Assigned tanvigour  as requested in #143

**Comment by XavierGeerinck** [comment]
https://github.com/dapr/dapr/issues/2988#issuecomment-881511141

**Comment by tanvigour** [comment]
Hey @XavierGeerinck Is this being worked on currently?

**Comment by XavierGeerinck** [comment]
Hi @tanvigour this is, but we are awaiting a dapr/dapr release to resolve issues in tests
