### ISSUE TITLE
CI : The test-e2e workflow passes even when the underlying e2e test fails.

### ISSUE THREAD

**Issue by Abhilash-Chandran** [dapr/js-sdk#145]
## Expected Behavior

When one of end-to-end tests fail then the workflow `test-e2e` should also fail. This is important when a new PR or commit is made to ensure there is no unintended impact due to the new changes.

## Actual Behavior

In its current form the `test-e2e` workflow passes even when the tests being run produce failures. 
This is due to the nature of how `dapr run` command suppress the exit status of the current app being run.

`dapr run` command doesn't doesn't exit when the underlying app exit with status code greater than 0. However for a github action step to fail, the exit code should be greater than 0.

The closest reference issue I can find is [this](https://github.com/dapr/cli/pull/683) in dapr/cli repo.

## Steps to Reproduce the Problem

Intentionally fail one of the tests in `actor.http.test.ts` or `main.http.test.ts` or `main.grpc.test.ts` and commit the file. This will trigger the `test-e2e` workflow. When looking at the results, it will show that the workflow has passed, however, the test inside would have failed.

>This doesn't affect the unit tests, as they are run independent of `dapr run` process. They naturally fail the workflow when one of those test fail.

## Possible Fix

> **Idea** : Scan the logs of each step for error.

In the run step for each test look for error in the console logs and explicitly fail the steps. An example is shown below.

```sh
# We need to do the following assertions as dapr run doesn't fail even if the underlying app exits with error.
# This ensures the workflow fails if any of the test fails, with error in logs.
# The grep command looks for the text "== APP == npm ERR!" text in the log. If found exits the step with code 1.
# This will fail the step.
- name: run grpc tests
  id: grpc_e2e
  run: |
	npm run test:e2e:grpc:main | tee test_grpc_out.txt &&
	if grep "== APP == npm ERR!" -i test_grpc_out.txt -q; then
	   exit 1;
	else
	   echo "No error found: All tests passed";
	fi              

- name: run http tests
  id: http_e2e      
  run: |
	npm run test:e2e:http:main | tee test_http_out.txt
	if grep "== APP == npm ERR!" -i test_http_out.txt -q; then
	   exit 1;
	else
	   echo "No error found: All tests passed";
	fi

- name: run actors tests
  id: http_actors_e2e      
  run: |
	npm run test:e2e:http:actors | tee test_http_actors_out.txt
	if grep "== APP == npm ERR!" -i test_http_actors_out.txt -q; then
	   exit 1;
	else
	   echo "No error found: All tests passed";
	fi
```

**Following fork contains the fix mentioned above and with different commits to test the fix which is working**

https://github.com/Abhilash-Chandran/js-sdk

If it looks correct I will create a PR. 😄 

BTW, I will be using this fix for dart-sdk 😉 , until I find an alternative.

**Comment by XavierGeerinck** [comment]
Thanks for reporting this issue! It's indeed an annoying one. I checked your proposal as well, but personally I am not a big fan of how this got fixed, it's a bit hacky in my opinion. The process should completely stop when an issue arises and throw the error up.

I need to investigate a bit deeper on how to solve this seeing the Dapr Sidecar injection. I will come back on this ASAP :)

**Comment by Abhilash-Chandran** [comment]
> Thanks for reporting this issue! It's indeed an annoying one. I checked your proposal as well, but personally I am not a big fan of how this got fixed, it's a bit hacky in my opinion. The process should completely stop when an issue arises and throw the error up.

Yes, the fix simply relies on a log and definitely just a workaround. But just noting it here so that its not missed. I checked the issues in Dapr Cli and there are still open issues trying to address this like this old [issue](https://github.com/dapr/cli/issues/190),  but I couldn't get a clear picture whether it can be dealt immediately. 

> I need to investigate a bit deeper on how to solve this seeing the Dapr Sidecar injection. I will come back on this ASAP :)

Sure, please take your time. I will keep my 👀 on this one.
