### ISSUE TITLE
Make Client and Server clearer through Docs

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#152]
## Describe the proposal

![image](https://user-images.githubusercontent.com/591282/149387777-40ad39f5-2a24-43cf-a15d-d6459a4c4d0a.png)

![image](https://user-images.githubusercontent.com/591282/149388106-40a29d3e-532c-4d55-922a-4f22231d1e52.png)

**Comment by XavierGeerinck** [comment]
![image](https://user-images.githubusercontent.com/591282/151600602-42441297-685e-436f-ba68-a65133a87d79.png)

**Comment by amulyavarote** [comment]
@XavierGeerinck Should we add this image to the readme and close this issue?

**Comment by XavierGeerinck** [comment]
Hi @amulyavarote yes, that would be great! :) do you know where we should add it?
