### ISSUE TITLE
Doc: Configuration API in JS-SDK

### ISSUE THREAD

**Issue by paulyuk** [dapr/js-sdk#160]
## Expected Behavior
The query API adding in v1.6 need documentation and code examples on how to use this API
See [PR #150.](https://github.com/dapr/js-sdk/pull/154)
Create:
- an example that shows this in JS - https://docs.dapr.io/developing-applications/building-blocks/configuration/howto-manage-configuration/
- add the sample to the main SDK doc: https://docs.dapr.io/developing-applications/sdks/js/js-client/#installing-and-importing-daprs-js-sdk

**Comment by amulyavarote** [comment]
@paulyuk The config API implementation PR is not merged. So the docs for this is missing. And What sample do we need in the main SDK? Any particular example we are targeting here? 

@XavierGeerinck Correct me if I am wrong.

**Comment by amulyavarote** [comment]
@XavierGeerinck We can update the docs once the configuration PR is merged.
