### ISSUE TITLE
Compilation problem in v2.0.0

### ISSUE THREAD

**Issue by guidoffm** [dapr/js-sdk#166]
In file:

https://github.com/dapr/js-sdk/blob/v2.0.0/src/types/StateQuery.type.ts

First line reads:

`import { Enumerable } from "./Enumerable.type"`

The referenced file does not exist.

**Comment by XavierGeerinck** [comment]
Should be fixed through PR #167 thanks for reporting! I will release 2.1.0 as soon as test finish running
