### ISSUE TITLE
SDK Version 2.0/2.0.1 Error TS2307: Cannot find module './StateOptions.type' or its corresponding type declarations

### ISSUE THREAD

**Issue by lechnerc77** [dapr/js-sdk#175]
## Expected Behavior

When executing `tsc` on a project with dapr client version 2.0 and 2.0.1 the build process should not run on a TS2307 error due to wrong imports.

## Actual Behavior

When executing `tsc` on a project with dapr client version 2.0 and 2.0.1 the build process should raises a TS2307 error due to wrong imports.

namely: 

```shell 
node_modules/dapr-client/types/Request.type.d.ts:3:31 - error TS2307: Cannot find module './StateOptions.type' or its corresponding type declarations.

3 import { IStateOptions } from "./StateOptions.type";
```

Reason is that the definition of IStateOptions is located at `./state/StateOptions.type`. The import in the file [Request.type.ts](https://github.com/dapr/js-sdk/blob/master/src/types/Request.type.ts) must be adjusted correspondingly:

```typescript
import { IEtag } from "./Etag.type";
import { IRequestMetadata } from "./RequestMetadata.type";
import { IStateOptions } from "./state/StateOptions.type";
export declare type IRequest = {
    key: string;
    value?: any;
    etag?: IEtag;
    metadata?: IRequestMetadata;
    options?: IStateOptions;
};

```

## Steps to Reproduce the Problem

Create a JavaScript project with the dapr client 2.0 or 2.0.1 and try to build the project

**Comment by lechnerc77** [comment]
Seems that there was a re-organization of the file [StateOptions.type.ts](https://github.com/dapr/js-sdk/blob/master/src/types/state/StateOptions.type.ts) as the imports in that file are also pointing to the wrong directory.

Must be: 

```typescript
import { EStateConsistency } from "../../enum/StateConsistency.enum";
import { EStateConcurrency } from "../../enum/StateConcurrency.enum";
export declare type IStateOptions = {
    concurrency: EStateConcurrency;
    consistency: EStateConsistency;
};

```

**Comment by shubham1172** [comment]
The code was introduced as part of https://github.com/dapr/js-sdk/pull/167, we should also investigate why the build step didn't fail.
/cc @XavierGeerinck

**Comment by lechnerc77** [comment]
I indeed did not check the build and test steps.

**Comment by lechnerc77** [comment]
@shubham1172 @XavierGeerinck : I think this is a general issue with the shell scripts that do not propagate errors.
I guess the expected behavior is that the script should abort when it hits an error (currently it silently ignores them). My proposal would be to put `set -e` at the entry of the script as this will also return the right status. For the `build.sh` this would look like:

```shell
#!/bin/bash

set -e

echo "====================================================="
echo "==================== Dapr JS SDK ===================="
echo "====================================================="
echo "Executing in $(pwd)"
echo "Description: Build the package in build/"
echo "====================================================="

# Prepare build
echo "Preparing Build"
rm -rf build/
mkdir build/

# @todo: gRPC binding pulling and building?
# echo ""
# echo "Building Protobuf"
# ./build-grpc.sh

# Build Package
echo "Building Library"
npm install > /dev/null
npm run lint > /dev/null
tsc --outDir ./build/ > /dev/null

# Prepare Publish
echo "Preparing Publish"
cp package.json build/
cp README.md build/

# Copy Proto Files
cp -R ./src/proto ./build
```
What do you think?

**Comment by shubham1172** [comment]
It does fail with `set -e` but it does not show any meaningful logs. The reason looks like the way we are handling output from commands.

``bash
command > /dev/null # will suppress all the output
```

For `npm install` and `npm lint`, we can continue to do so, but we should remove it for `tsc`.

**Comment by XavierGeerinck** [comment]
I agree,  there is something going on in the build step. I am not sure build.sh runs during the tests either, but there is a more to it. I added a reference to the new isseu 177 so we can close this one for now
