### ISSUE TITLE
Fix tests and build process for catching errors

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#177]
## Expected Behavior

* [x] Errors should be caught when build fails or transpilation
* [x] Errors from tests should be caught
* [x] Should be able to open a dev container and run `./scripts/build.sh`

## Actual Behavior

We are not capturing them correctly:
1. The Dapr sidecar is there which makes it harder to receive errors since we run `jest` without erroring on test failure due to `TCPWRAP` and alike kind of issues
2. When the build fails we do not catch it correctly

> Ref follow up of #175

**Comment by shubham1172** [comment]
For failing `build.sh` on compilation error, per #175, we should
1. add `set -e` to fail build.sh on error (as suggested by @lechnerc77)
2. not redirect output from `tsc` to `/dev/null` to show meaningful failure logs

**Comment by XavierGeerinck** [comment]
Partially fixed by PR #183 , Sidecar issue remains open
