### ISSUE TITLE
Multiple Issues when building project

### ISSUE THREAD

**Issue by lechnerc77** [dapr/js-sdk#183]
## Expected Behavior

When starting the project in a dev container and executing the script `./scripts/build.sh` the build should be executed without errors. 

## Actual Behavior

Build fails due to different errors:

1. `./scripts/build.sh: line 26: tsc: command not found`  - This is due to the fact that the devcontainer does not have TypeScript installed globally (necessary as it is called via `tsc` in the build script), only locally. Possible solution is to replace the `tsc`in the script via `npx tsc`
2. When replacing via `npx tsc` a build error is raised:
    ```shell
    src/types/metadata/GetMetadataResponse.ts:6:13 - error TS2304: Cannot find name 'KeyValueType'.
    6   extended: KeyValueType;
              ~~~~~~~~~~~~
    src/types/metadata/GetMetadataResponse.ts:6:13 - error TS4033: Property 'extended' of exported interface has or is using private 
    name 'KeyValueType'.

    6   extended: KeyValueType;
    ```  
    Here it seems that the imported type `KeyValuePairType` is set as `KeyValueType` - the **Pair** is missing
3. Fixing the error in 2. lead to another error:
    ```shell
    src/implementation/Client/GRPCClient/metadata.ts:30:11 - error TS2739: Type '{}' is missing the following properties from type 
    'KeyValuePairType': key, value
    
    30           extended: res.getExtendedMetadataMap().toObject().reduce((result: object, [key, value]) => {
                 ~~~~~~~~

      src/types/metadata/GetMetadataResponse.ts:6:3
        6   extended: KeyValuePairType;
            ~~~~~~~~
        The expected type comes from property 'extended' which is declared here on type 'GetMetadataResponse'
    ```
    Here I stopped my investigations :-)
    
=> I would highly recommend to fix the build pipeline as described in issue #177. Fix available via PR  #182    

## Steps to Reproduce the Problem

* Clone the repository
* Open the cloned repository in a dev container
* Execute the script `./scripts/build.sh`  in the dev container

**Comment by XavierGeerinck** [comment]
Closing in favor of #177
