### ISSUE TITLE
Improve Dapr-Bot

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#208]
## Describe the proposal

We could improve the Dapr Bot for Repo Management with the following:

* `stale is fine`: Mark an issue as stale when it is not being responded to in X days
* `needs-author-feedback`: Add the tag when a comment is made with `/ping-author` by a contributor. This will then add the label `needs-author-feedback` to the issue.
* `needs-team-attention`: Add the tag when the Author of the issue replies to a comment that added the label `needs-author-feedback`. It will as well remove the tag `needs-author-feedback`

**Comment by shubham1172** [comment]
Additionally, add a `/ok-to-e2e-test` command.

**Comment by tanvigour** [comment]
> Additionally, add a `/ok-to-e2e-test` command.

Doesn't ok-to-test do that?

**Comment by shubham1172** [comment]
@tanvigour, we don't have these currently in this repo's dapr bot.
