### ISSUE TITLE
Support customized header for invoker

### ISSUE THREAD

**Issue by Halomaple** [dapr/js-sdk#218]
In many cases we need passing some params like `X-UserId` from web to backend in HTTP header, but current implementation of js-sdk is **blocking** the header. 
See `src/implementation/Client/HTTPClient/invoker.ts` line 31-36: 
```js
    if (method !== HttpMethod.GET) {
      // @ts-ignore
      fetchOptions.headers = {
        'Content-Type': 'application/json'
      };
    }
```

So I wonder whether we can add new param named header in function `invoke` to support this? 
Like `async invoke(appId: string, methodName: string, method: HttpMethod = HttpMethod.GET, data: object = {}, header = {}): Promise<object> {}`

**Comment by shubham1172** [comment]
I support this request. It is something already supported by dotnet-sdk https://github.com/dapr/dotnet-sdk/issues/396

**Comment by pnocera** [comment]
I did a fork and implemented it. That is 6 lines of code....could submit a PR eventually.

**Comment by shubham1172** [comment]
@pnocera that's great, feel free to raise a PR. Thank you for helping out!
