### ISSUE TITLE
documentation: overhaul README.md

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#236]
## Describe the proposal

It appears that the documentation is still a bit confusing. I would propose to overhaul the README in the following way:

* General introduction of what the Dapr JS SDK is
* Quick getting started example
* Link to the main docs.dapr.io page and steering people there
    * Maybe we can add a table to the different sections that each link to docs.dapr.io?
    * I would also love to include "Dapr Integerations" e.g. how to integrate with Nest.js, ...
* Link to companies using the Dapr JS SDK? 
* Link to blog articles using the Dapr JS SDK?
* References

Thoughts?  

- [ ] Update the Dapr docs to point to the latest index.md file and have a good overview on docs.dapr.io

**Comment by XavierGeerinck** [comment]
@shubham1172 @amulyavarote @tanvigour

**Comment by XavierGeerinck** [comment]
Might be a good idea indeed :-) not entirely sure as it involves running docker containers so developers running these should ensure they don't have port blocks

**Comment by johnnyreilly** [comment]
Tiny thing, but it might be an idea to have installation instructions? eg

`npm install dapr-client --save`

I say this as the name of the repo is `js-sdk` and I couldn't immediately work out what the named of the published package was

**Comment by shubham1172** [comment]
Thanks for the feedback @johnnyreilly, it's being added as a part of #223

**Comment by XavierGeerinck** [comment]
@johnnyreilly the first PR for this has now been pushed, feel free to check and help us ensure it is clear enough
