### ISSUE TITLE
Add warning message to `dapr-client` builds

### ISSUE THREAD

**Issue by shubham1172** [dapr/js-sdk#260]
## Proposal

Per #207, add deprecation warnings to the `dapr-client` package builds and direct the user to move to `@dapr/dapr`.

**Comment by XavierGeerinck** [comment]
Linked to #261

**Comment by shubham1172** [comment]
npm postinstall scripts have stopped echoing to the terminal, see https://github.com/npm/cli/issues/3647

Another option for this is to use [npm deprecate]https://docs.npmjs.com/cli/v8/commands/npm-deprecate). We will need something like this:

```bash
npm deprecate dapr-client@ "dapr-client is deprecated. Please use @dapr/dapr instead. For more information, see https://github.com/dapr/js-sdk/issues/259".
```

@XavierGeerinck do you want to do this?

**Comment by XavierGeerinck** [comment]
I can't... I don't have access to the `dapr-client` package

**Comment by shubham1172** [comment]
Hello @XavierGeerinck, the versioning feature request is now being tracked separately. The PR for warning users on using dapr-client package is up and will close this issue.
