### ISSUE TITLE
HTTP Client invoker POST conditional is always true

### ISSUE THREAD

**Issue by rzyns** [dapr/js-sdk#262]
I was just browsing the code and noticed this.

https://github.com/dapr/js-sdk/blob/e4f8245f5af1d5bca10a7384c39c61449639ea82/src/implementation/Client/HTTPClient/invoker.ts#L38-L41

`data !== {}` will always evaluate to `true` since objects are compared by reference. The closest drop-in replacement I can think of off the top of my head is to use `!Object.keys(data).length`, but it would probably be better to change the default value of the `data` parameter. Something like:

```typescript
  async invoke(appId: string, methodName: string, method: HttpMethod = HttpMethod.GET, data?: object): Promise<object> {
    // ...
    if (method !== HttpMethod.GET && data != null) {
      // @ts-ignore
      fetchOptions.body = JSON.stringify(data);
    }
```

**Note:** I like `!= null` because it will match both `null` and `undefined`.

**_EDIT:_** _Thinking in terms of baseline positive equality, I originally wrote `true` instead of `false` above. This has been corrected._ 😖

**Comment by rzyns** [comment]
I'll create a PR to this when I get a chance

**Comment by shubham1172** [comment]
It seems the other way, i.e. `data !== {}` will always evaluate to `true`. From my console:
![image](https://user-images.githubusercontent.com/22132944/168440218-ac9f03a6-0a8e-4eb6-8e44-d46254c5eb98.png)

Also, this e2e test always passes, which means `data !== {}` must have been `true` here as well.

https://github.com/dapr/js-sdk/blob/c3eebe014614e98b524d7d72b45dbc0f27f2be26/test/e2e/main.http.test.ts#L127-L141

**Comment by XavierGeerinck** [comment]
AFter discussing in weekly: might indeed be interesting to have typescript with `data?: object = null` and then check if data is `null`
