### ISSUE TITLE
2.2.0 is broken - "cannot find module dapr-client"

### ISSUE THREAD

**Issue by orgalaf** [dapr/js-sdk#263]
## Expected Behavior

When importing like this
```
import { CommunicationProtocolEnum, DaprClient, HttpMethod } from 'dapr-client';
```
I expect typescript to recognize the import.

## Actual Behavior

Typescript does not find the module and definitions. Building the project fails saying it cannot find the module.

## Steps to Reproduce the Problem

Install 2.2.0 and try to import into a ts file and build.

## Current fix

Fall back to 2.1.0

**Comment by XavierGeerinck** [comment]
Thanks a lot for reporting this, we have resolved this issue now!

We also would like to notify you that we are switching to the [`@dapr/dapr` npm package](https://www.npmjs.com/package/@dapr/dapr) in the future, so feel free to use that package whenever possible :) (both packages will remain working for the time being)
