### ISSUE TITLE
Update DaprClient and DaprServer API for easier usage

### ISSUE THREAD

**Issue by shubham1172** [dapr/js-sdk#294]
## Describe the proposal

The current `DaprClient` API looks like this:
```ts
 constructor(
    daprHost?: string
    , daprPort?: string
    , communicationProtocol: CommunicationProtocolEnum = CommunicationProtocolEnum.HTTP
    , options: DaprClientOptions = {},
  )
```

Since typescript does not have support for named parameters, skipping one parameter and adding the next one will result in something like this on the consumer end:
```ts
var clientOptions = {logger: {level: LogLevel.Debug}}
const client = new DaprClient(
    daprHost,
    undefined, // default is process.env.DAPR_HTTP_PORT ?? 3500
    undefined, // default is CommunicationProtocolEnum.HTTP
    clientOptions);
```

The proposal is to move to a more friendlier `DaprClient` API:
```ts
 constructor(DaprClientOptions)
// ...
export type DaprClientOptions = {
  daprHost?: string;
  daprPort?: string;
  communicationProtocol: CommunicationProtocolEnum;
  isKeepAlive?: boolean;
  logger?: LoggerOptions;
}
```

This will allow consumers to instantiate `DaprClient` as follows:
```ts
const client = new DaprClient({
    daprHost:daprHost,
    logger:loggerOptions});
```

Similar exercise proposed for `DaprServer`.

**Comment by salmankhan-prs** [comment]
Hi @shubham1172  changes should be reflect in test cases to ?

**Comment by shubham1172** [comment]
> Hi @shubham1172 changes should be reflect in test cases to ?

Yes, this proposal requires a broader discussion before any implementation, feel free to add them to this thread/join our [community calls](https://github.com/dapr/js-sdk/wiki/Community-engagement) and talk about it.
