### ISSUE TITLE
Add metadata to save field

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#302]
## Expected Behavior

Should be able to use save with metadata

## Actual Behavior

We only allow key and value so cannot do this

## Steps to Reproduce the Problem

```javascript
    await daprClient.state.save(Config?.dapr?.components?.state?.cosmos?.name, [
      {
        key: "test",
        value: { hello: "world", partitionID: 2083 },
        metadata: {
          partitionKey: "partitionID"
        }
      }
    ])
```

Will result in

```
== APP == Error: {"errorCode":"ERR_STATE_SAVE","message":"failed saving state in state store state-azure-cosmosdb: BadRequest, Message: {\"Errors\":[\"PartitionKey extracted from document doesn't match the one specified in the header. Learn more: https:\\/\\/aka.ms\\/CosmosDB\\/sql\\/errors\\/wrong-pk-value\"]}\r\nActivityId
```

**Comment by shubham1172** [comment]
@XavierGeerinck this has worked for me with transactions. https://github.com/shubham1172/dapr-cosmos-example/blob/reproduce-issue-1209/src/index.ts

Can you please share the partition key from the Cosmos DB portal on Azure?

**Comment by XavierGeerinck** [comment]
![image](https://user-images.githubusercontent.com/591282/174455257-f4e70c96-a42a-4446-9927-4c43e018f9c7.png)

**Comment by XavierGeerinck** [comment]
Tracking the PartitionKey not working in https://github.com/dapr/components-contrib/issues/1794

For the JS SDK we should implement the metadata part (see fetch example in the issue above)

**Comment by shubham1172** [comment]
Got it, thanks!

**Comment by XavierGeerinck** [comment]
For follow-up: https://github.com/dapr/components-contrib/issues/1794
