### ISSUE TITLE
During local development, how can I simultaneously debug multiple services?

### ISSUE THREAD

**Issue by orgal-ea** [dapr/js-sdk#305]
### My scenario: 
I have N daprized services and all of them act as both a server and a client, and I want to be able to debug multiple services locally at the same time.

### The challenge: 
In order to debug them in parallel I must run a sidecar for each of them. This means I need to manually allocate a different `dapr-http-port` to each sidecar in addition to manually allocating different `app-ports`. In addition to that I need to hold a config to tell each client at which `dapr-http-port` to find the sidecar of the dapr server running each target method.

### The question: 
Is there a better way? What would be the recommended approach?
Some thoughts I've had:
- Create a dapr-mock lib and use that locally and during testing. Seems like the least involved option and most transparent to developers.
- Create a docker-compose to run all my local sidecars. Would still require manual or automatic port allocation. And would require developer to add a sidecar definition to that docker-compose when creating a new service.
- Create some more advanced tooling to dynamically create local sidecars with dynamic ports and some kind of local method->port discovery which the services can use.

Any input would be much appreciated. Thanks!

**Comment by XavierGeerinck** [comment]
I create a service map that shows the ports and I then put those in the npm run command

you could normally use dynamic ports but it’s easier to know the ports as you can then debug it more easily and call manually as well

I do this for a production workload with ~7 services
