### ISSUE TITLE
Module '"http"' has no default export

### ISSUE THREAD

**Issue by webup** [dapr/js-sdk#307]
## Expected Behavior

`@dapr/dapr` 2.3.0 could be compiled correctly with ts, to achieve this, we should use `import * as http` instead of directly `import http`.

## Actual Behavior

When executing `tsc`, `node_modules/@dapr/dapr/types/http/THTTPExecuteParams.type.d.ts` reports error:
- `Module '"http"' has no default export`
- `Module '"https"' has no default export`

## Steps to Reproduce the Problem

npm install dapr and run tsc, just as this [job](https://github.com/OpenFunction/functions-framework-nodejs/runs/7019916254?check_suite_focus=true#step:7:97) shows.

**Comment by shubham1172** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/3337 for more context on the issue.

**Comment by shubham1172** [comment]
Also FYI we didn't catch this in Dapr because we have `allowSyntheticDefaultImports` enabled in our typescript configuration via `"esModuleInterop": true`. See https://github.com/microsoft/TypeScript/pull/5577 for more.
