### ISSUE TITLE
Update proto files for 0.8.0 release

### ISSUE THREAD

**Issue by youngbupark** [dapr/js-sdk#31]
## Describe the proposal

Update proto files for 0.8.0 release

**Comment by youngbupark** [comment]
@pruthvidhodda Can you please help this issue?

**Comment by pruthvidhodda** [comment]
> @pruthvidhodda Can you please help this issue?

Sure, I believe the protobufs and gRPC code also needs to be updated as part of this issue?

I'll start on this as we approach closer to the release date allowing any possible changes to protos.

**Comment by youngbupark** [comment]
> > @pruthvidhodda Can you please help this issue?
> 
> Sure, I believe the protobufs and gRPC code also needs to be updated as part of this issue?
> 
> I'll start on this as we approach closer to the release date allowing any possible changes to protos.

👍

**Comment by pruthvidhodda** [comment]
Re-opening as protos for bi-directional bindings got updated in dapr/dapr
