### ISSUE TITLE
can't send msg >4mb

### ISSUE THREAD

**Issue by giang12** [dapr/js-sdk#330]
## Expected Behavior
to be able to invoke/pub with req size > 4mb fixed...for both http and grpc clients
## Actual Behavior
 grpc client:  error "code": 8,
    "details": "Received message larger than max (6632286 vs. 4194304)",
http client: nothing happen.. return undefined...

## Steps to Reproduce the Problem
try invoke remote services via sidecar and see...
seem like missing 3rd options params for grpc client https://github.com/dapr/js-sdk/blob/7bf1bb8e965fee48144e6f9b5707f39e6cf4950b/src/implementation/Client/GRPCClient/GRPCClient.ts#L76

**Comment by giang12** [comment]
try setting 
grpc.max_send_message_length
grpc.max_receive_message_length
from https://www.npmjs.com/package/@grpc/grpc-js..as gathered from https://github.com/dapr/js-sdk/issues/70
still no success..

**Comment by XavierGeerinck** [comment]
Can you list your Dapr run command?

**Comment by giang12** [comment]
`dapr run --app-id ingress-app --app-port 8080 --dapr-grpc-port 3500 --dapr-http-max-request-size 20 -- node bin/cli.js`
(there is no equivalent --dapr-hrpc-max-request-size?)
tx for getting back so quickly

**Comment by giang12** [comment]
https://github.com/alvinhenrick/go-sdk/blob/52e8721128799f3ad77136c6d82e4f769692be26/examples/service/custom-grpc-client/main.go#L29 i saw in go-sdk they recommend manually setting up grpc conns https://github.com/dapr/go-sdk/pull/197

**Comment by shubham1172** [comment]
Hello @giang12, is HTTP mode working with `--dapr-http-max-request-size`?

**Comment by giang12** [comment]
hi @shubham1172 no unfortunately.. just tried again to make sure. I ran both sender and receiver in http mode like this 
dapr run --app-id ingress-app --app-port 8080 --dapr-http-port 3500 --dapr-http-max-request-size 44 -- node bin/cli.js
`dapr run --app-id echo-app --app-protocol http  --app-port 50051 --dapr-http-port 3503 --dapr-http-max-request-size 44 -- node dist/index.js`
![image](https://user-images.githubusercontent.com/5290460/180907184-e95ad814-ec38-4bff-bc94-5d28b9400116.png)
never reached 2nd console.log..just return without any error somehow, just an empty `{}`

**Comment by shubham1172** [comment]
Is it possible for you to share a Minimal, Reproducible Example? I can run this on my end and check.

**Comment by giang12** [comment]
zip attached 
[sample.zip](https://github.com/dapr/js-sdk/files/9186336/sample.zip)

tried sending to "go" app; same behavior

**Comment by XavierGeerinck** [comment]
So, if I understand correctly, the scenario is from client -> invoke -> server

This would mean we need to implement `https://github.com/dapr/js-sdk/blob/7bf1bb8e965fee48144e6f9b5707f39e6cf4950b/src/implementation/Server/HTTPServer/HTTPServer.ts#L48` correctly where the `bodyParser` utilizes `limit` (e.g. `app.use(bodyParser.json({limit: '50mb'}));`)

For gRPC some more research is required though, theoretically we need to pass options flags (such as the below)

```python
channel = grpc.insecure_channel(
    'localhost:50051',
    options=[
        ('grpc.max_send_message_length', MAX_MESSAGE_LENGTH),
        ('grpc.max_receive_message_length', MAX_MESSAGE_LENGTH),
    ],
)
```

The workaround for this is to create your own custom HTTP server that utilizes the `limit` functionality.

**Comment by giang12** [comment]
yeah accepting custom http servers/grpc conns seem to be simplest
