### ISSUE TITLE
GRPCClient doesn't pass metadata to binding: unable to send data to Redis Output Binding

### ISSUE THREAD

**Issue by alecor191** [dapr/js-sdk#339]
## Expected Behavior

When sending data to a Redis Output Binding using `DaprClient`, data is successfully accepted by Redis.

## Actual Behavior

Sending data to Redis Output Binding fails, as the provided `key` metadata value doesn't seem to get forwarded to Redis. As this is a mandatory metadata field, Redis binding fails with the following error:

```
Error: 13 INTERNAL: error when invoke output binding node-sub-app-blob: redis binding: missing key on write request metadata
```

## Steps to Reproduce the Problem

1. Have Dapr CLI installed
2. Create an Output Binding as follows:

  ```yaml
  apiVersion: dapr.io/v1alpha1
  kind: Component
  metadata:
    name: my-redis-binding
  spec:
    type: bindings.redis
    version: v1
    metadata:
      - name: redisHost
        value: localhost:6379
      - name: redisPassword
        value: ""
  ```

3. Create some simple NodeJS app and use the following code to send some data to the Redis binding:

  ```typescript
  const client = new DaprClient(daprHost, daprGrpcPort, CommunicationProtocolEnum.GRPC);
  
  await client.binding.send(
      "my-redis-binding",
      "create",
      "some message",
      { key: "my-key" });
  ```

4. The `send` request fails with the error message mentioned above.

## Additional information

- @dapr/dapr package version `2.3.1` used
- Dapr CLI version `1.8.1`
- I used Python SDK to do the same as above and it works fine.
- Briefly looking at `@dapr\dapr\implementation\Client\GRPCClient\binding.js` seems to give some hints, that the provided metadata values are not used (yet)? Notice `@todo` message as well as `_metadata` parameter not being used.

```typescript
    // Send an event to an external system
    // @todo: should pass the metadata object <<<===== NOT SUPPORTED YET?
    // @todo: should return a specific typed Promise<TypeBindingResponse> instead of Promise<object>
    send(bindingName, operation, data, _metadata = {}) {  <<<===== _metadata not used?
        return __awaiter(this, void 0, void 0, function* () {
            const msgService = new dapr_pb_1.InvokeBindingRequest();
            msgService.setName(bindingName);
            msgService.setOperation(operation);
            msgService.setData(SerializerUtil.serializeGrpc(data).serializedData);
            const client = yield this.client.getClient();
            return new Promise((resolve, reject) => {
                client.invokeBinding(msgService, (err, res) => {
                    if (err) {
                        return reject(err);
                    }
                    // https://docs.dapr.io/reference/api/bindings_api/#payload
                    return resolve({
                        data: res.getData(),
                        metadata: res.getMetadataMap(),
                        operation
                    });
                });
            });
        });
    }
```

**Comment by shubham1172** [comment]
Thank you for this issue @alecor191! Once https://github.com/dapr/js-sdk/pull/329 is closed, this can be re-used here to convert key-value metadata to gRPC metadata.
 https://github.com/dapr/js-sdk/blob/23aeadd54a69502d62474f83fb3785ac4295de70/src/utils/Client.util.ts#L22-L28
