### ISSUE TITLE
v3.0.0 deprecate req.body.data in favor of req.body on pub/sub

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#343]
## Describe the proposal

We need to deprecate returning req.body.data in favor of req.body on the pubsub API to support components that don't utilize req.body.data

https://github.com/dapr/js-sdk/blob/main/src/implementation/Server/HTTPServer/HTTPServerImpl.ts#L91

**Comment by XavierGeerinck** [comment]
Keep Alive

**Comment by salmankhan-prs** [comment]
@shubham1172  Here I haven't understood what to do exactly But as per the above description, I got to know that we have to return only **req.body** i.e,
`   const data = req?.body?.data || req?.body;
`
to
`const data = req?.body;
`
@shubham1172  can you give some more input on this

**Comment by XavierGeerinck** [comment]
Hi a PR has been opened for this https://github.com/dapr/js-sdk/pull/426

**Comment by XavierGeerinck** [comment]
Tackled in #443
