### ISSUE TITLE
DaprClient in "awaiting sidecar to be started" does not use specified logger from DaprServer

### ISSUE THREAD

**Issue by TheAifam5** [dapr/js-sdk#354]
## Expected Behavior

In previous versions, when instantiating DaprServer, a message "awaiting sidecar to be started" went through a logger specified in clientOptions (constructor parameter in DaprServer) which allowed to transform it to json format in my case.

## Actual Behavior

Currently when in such state, it uses it's own defined logger (DaprClient.ts:153) and ignores the specified logger service. There is no other way to override it.

## Steps to Reproduce the Problem

1. Instantiate new DaprServer with logger service
2. Start the application without Dapr Sidecar

Result: HTTPServer logs goes through the specified logger service, DaprClient is printed with a default logger from Dapr package.

Related: #324
Affected Tags: 2.3.1
Last working version: 2.3.0

**Comment by shubham1172** [comment]
Thanks for catching this, @TheAifam5!
