### ISSUE TITLE
Bulk PubSub implementation in SDK

### ISSUE THREAD

**Issue by shubham1172** [dapr/js-sdk#360]
# Proposal

Create a new bulk PubSub implementation, runtime issue: https://github.com/dapr/dapr/issues/2218

**Comment by XavierGeerinck** [comment]
Awaiting dapr/dapr I guess?

**Comment by shubham1172** [comment]
Yes, added @XavierGeerinck, thanks!

**Comment by XavierGeerinck** [comment]
Awaiting 1.10 release, might switch this to SDK v3.1.0
