### ISSUE TITLE
Add DAPR_API_TOKEN to HttpClient

### ISSUE THREAD

**Issue by ahmedhesham6** [dapr/js-sdk#363]
## Describe the proposal
- Extend HttpClient to add DAPR_API_TOKEN as http header

**Comment by shubham1172** [comment]
Docs: https://github.com/dapr/docs/blob/v1.9/daprdocs/content/en/operations/security/api-token.md

Related: #282

**Comment by XavierGeerinck** [comment]
Closing in favor of #282
