### ISSUE TITLE
[INVOCATION] There should be an option to pass headers during invocation.

### ISSUE THREAD

**Issue by salmankhan-prs** [dapr/js-sdk#366]
At the moment, we can pass the body while performing service invocation. Headers cannot be passed. I believe the invoke function should also accept a headers parameter so that users can pass headers.

**Comment by shubham1172** [comment]
Duplicate https://github.com/dapr/js-sdk/issues/218

**Comment by salmankhan-prs** [comment]
@shubham1172 I think the #218 issue is not solved yet. right?

**Comment by shubham1172** [comment]
That's right, @salmankhan-prs.

**Comment by salmankhan-prs** [comment]
@shubham1172  This is something that I can figure out.

**Comment by shubham1172** [comment]
A PR is always welcome! You can refer to https://github.com/dapr/js-sdk/pull/257, it was closed due to inactivity and some comments were to be fixed.
