### ISSUE TITLE
How to set CloudEvent `type` attribute when working with JS SDK pubsub?

### ISSUE THREAD

**Issue by alecor191** [dapr/js-sdk#370]
[Dapr docs](https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-cloudevents/) mention that Dapr automatically wraps payload sent to a pubsub component in a CloudEvent v1.0 envelope.

With that, I wanted to achieve the following:

*Leverage the CloudEvent `type` attribute to specify the schema version of a message (similar to the [Dapr docs example](https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-route-messages/#example-expressions) that sets `event.type == "mymessage.v1"`).*

The approach would be:

- The publishing service uses Dapr JS SDK's `DaprClient.pubsub.publish()` to publish a message. 
  ===> *Here I don't see how I could set `type` attribute of the wrapping CloudEvent envelope.*
- The subscribing service uses Dapr JS SDK's `DaprServer.pubsub.subscribe()` to receive messages and then based on `type` determine how to parse the message.
  ===> *While the [Dapr docs example](https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-route-messages/) example shows how to do this declaratively or by providing a `/dapr/subscribe` endpoint, I don't see how I could accomplish something similar using the Dapr JS SDK; or how I could use the callback to inspect CloudEvent attributes. The callback only gets the already unwrapped message payload*

Could you please shed some light on how to leverage Dapr JS SDK to set/read CloudEvent properties?

**Comment by shubham1172** [comment]
Hello @alecor191, as of today JS-SDK does not support publishing cloud events directly. I have created #371 to track it. As a workaround, you can use HTTP client to publish a cloud event directly.

For subscriber side, see https://github.com/dapr/js-sdk/blob/main/daprdocs/content/en/js-sdk-docs/js-client/_index.md#subscribe-to-messages-rule-based - this document will be soon updated in the official docs website.

**Comment by alecor191** [comment]
Thanks @shubham1172!
