### ISSUE TITLE
fix: Invalid 'main' field in package.json

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#382]
== APP == (node:18159) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/xaviergeerinck/Projects/MASKED/backoffice/backend/node_modules/@dapr/dapr/package.json' of './build/index.js'. Please either fix that or report it to the module author

**Comment by shubham1172** [comment]
https://github.com/dapr/js-sdk/pull/377 fixing as part of updating package.json here.
