### ISSUE TITLE
Signal a pubsub message for retry with SDK

### ISSUE THREAD

**Issue by danielgerlag** [dapr/js-sdk#416]
Is it possible to signal that you would like to retry a pubsub message that you are consuming using the JS SDK

```js
const server = new dapr.DaprServer();  
await server.pubsub.subscribe("pubsub", "topic", async (data) => {
    throw new Error("Please retry???");
});
  
await server.start();
```

**Comment by shubham1172** [comment]
This is currently unsupported, but we can move it to v3.0.0. We can return a response (drop/success/retry) instead of the throwing error (which can handle success and error today).

**Comment by XavierGeerinck** [comment]
Closing in favor of #338
