### ISSUE TITLE
Add unsubscribe method for Configuration API

### ISSUE THREAD

**Issue by sarsharma** [dapr/js-sdk#421]
## Describe the proposal

JS-SDK returns a stream when we subscribe to configuration changes 
https://github.com/dapr/js-sdk/blob/f9571d5b34f5b1f41a06ba9b9b4da0c2c0f3fb36/src/implementation/Client/GRPCClient/configuration.ts#L75
However, it does not implement a `unsubscribe()` method similar to other SDKs. We need to stop the stream to stop listening for config updates. 

Python : https://github.com/dapr/python-sdk/blob/3d9b155af142fd531be95ceb0e2fccd237e630c2/dapr/clients/grpc/client.py#L976-L979
Golang : https://github.com/dapr/go-sdk/blob/c2dfec6abfd5b3049c83703af9dea067036f50bc/client/client.go#L129-L130 

Can we add a similar unsubscribe method for JS-SDK ?

**Comment by sarsharma** [comment]
cc: @shivamkm07 @akhilac1

**Comment by XavierGeerinck** [comment]
Closing as we do support unsubscribing. An object is returned on subscribe containing the stop method

https://github.com/dapr/js-sdk/blob/main/src/implementation/Client/GRPCClient/configuration.ts#L146

**Comment by shubham1172** [comment]
@sarsharma, as an application dev, one can choose to maintain a map of subscription IDs to the stop callbacks in-memory and achieve the same functionality, but adding this to the SDK will be an overhead.
