### ISSUE TITLE
Pubsub: If callback fails, JS SDK still treats message as processed successfully (no retries)

### ISSUE THREAD

**Issue by alecor191** [dapr/js-sdk#451]
## Expected Behavior

When a pubsub subscription callback fails (throws), Dapr should _not_ acknowledge the message as processed. Instead, it should let the pubsub component know that the messages failed to process.

## Actual Behavior

If the callback function throws, Dapr JS SDK still seems to indicate to the pubsub component that the message was processed successfully. Thus, the pubsub component (Azure ServiceBus Topic in my case), removes the message from the topic/queue (instead of retrying or eventually moving it to the dead letter queue).

This is quite a critical issue, as the point of leveraging a pubsub is to add resiliency to an app in case of failure.

## Steps to Reproduce the Problem

- Create simple pubsub with Azure ServiceBus Topic (also reproduced with Redis for me)
- Create app using JS SDK that subscribes to the pubsub
- In the subscription callback, throw an exception
-> that message will never be provided to the subscription callback again. It's treated as "processed" and removed from the pubsub.

**Note**: The behavior above is _not_ reproducible with .NET SDK. There it behaves as expected: i.e. callbacks throwing exceptions lead to pubsub component to retry. Thus, it leads me to believe that this is not a Dapr issue, but a JS SDK one.

Or is there another way a subscription callback can indicate failure than throwing?

**Comment by XavierGeerinck** [comment]
Related to #338

**Comment by alecor191** [comment]
Thanks a lot @XavierGeerinck for the super-fast triage. Is 3.0.0 still on track for a February release (took that date from the [milestone description](https://github.com/dapr/js-sdk/milestone/5))?

**Comment by XavierGeerinck** [comment]
Yes it is! We are doing our ultimate best to get it out of the door this month
