### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by ryan-z** [dapr/js-sdk#464]
Hello there! I noticed there hasn't been a release since last November, despite some code changes that were merged into the main branch. My situation is that my pubsub project has cloudevents that I want to combine with Dapr's cloudevents, and I'd like to start using the client SDK instead of doing a manual fetch (or cloudevent emitter) to set the content type.
Would it be possible to bump a new minor release so I can do something like [this](https://github.com/dapr/js-sdk/pull/428/files#diff-e96900ba76510cb65cc3a02343d049c920835dfeae9e9ce0abdbe21cf788dbbeR286-R292)?

**Comment by shubham1172** [comment]
@ryan-z do checkout the latest release https://github.com/dapr/js-sdk/releases
