### ISSUE TITLE
Update quickstarts and dapr docs with v3.0.0 SDK version

### ISSUE THREAD

**Issue by shubham1172** [dapr/js-sdk#469]
## Describe the proposal

Update quickstarts and dapr docs JS-SDK snippets, using v3.0.0

Related https://github.com/dapr/quickstarts/issues/818, https://github.com/dapr/docs/issues/3280

**Comment by wralith** [comment]
I can do this task if you haven't started yet

**Comment by shubham1172** [comment]
@wralith hello and welcome 👋🏻 please feel free to start it, let me know and I will assign this to you!

**Comment by wralith** [comment]
dapr/quickstarts#824, dapr/docs#3333

**Comment by XavierGeerinck** [comment]
Closing as it is merged or was approved
