### ISSUE TITLE
[docs] Add actors to SDK interaction

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#470]
## Describe the proposal

Explain more visually how actors interact with the sidecar

This is Actor Runtime <> SDK <> Sidecar 
Sidecar takes care of "reminding", "timing", ... to the SDK and the SDK then propagates the event to the actor instance
The actor can then talk to the sidecar through the SDK for State management and others
The Sidecar is an isolated process, while SDK and Runtime are on the same process

**Comment by shubham1172** [comment]
👋🏻
