### ISSUE TITLE
[Crypto] Implement support for EncryptAlpha1/DecryptAlpha1 APIs

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/js-sdk#474]
dapr/dapr#6197 implements two new APIs in Dapr:

- `EncryptAlpha1`
- `DecryptAlpha1`

Both APIs are stream-based, so the SDK is expected to read input as a stream, send it to Dapr using a streamed gRPC in chunks, and in parallel read the response from Dapr (in chunks sent over the same gRPC stream) and return a readable stream to the caller.

The reference implementation is in the Go SDK: dapr/go-sdk#387

**Comment by salmankhan-prs** [comment]
@shubham1172  can you provide some more information on this isssue in the context of js-sdk

**Comment by shubham1172** [comment]
Hi @salmankhan-prs, looks like you have to create a bi-directional gRPC stream to talk to Dapr. See configuration API for example, we use a uni-directional stream to send messages on subscribe https://github.com/dapr/js-sdk/blob/d742c36843e6d0968122e4454e4e4d40d6b3f91b/src/implementation/Client/GRPCClient/configuration.ts#L125

This documentation talks about bi-directional streaming as well - https://grpc.io/docs/languages/node/basics/
Also the reference implementation in Go will be useful (linked above).

**Comment by salmankhan-prs** [comment]
Okay, @shubham1172  I will start by doing a little bit of research on the bi-directional gRPC stream. Then I will try to work on this
