### ISSUE TITLE
Supporting optional attributes in state management

### ISSUE THREAD

**Issue by SoTrx** [dapr/js-sdk#475]
## Describe the proposal
Implement the optional behavior attributes in the State Management API (https://docs.dapr.io/reference/api/state_api/#optional-behaviors)

Looking at the code, this is already partially done, and I'd be happy to help

**Comment by shubham1172** [comment]
@SoTrx thanks for opening this issue, it looks like the options exist here [state/StateOptions.type.ts](https://github.com/dapr/js-sdk/blob/main/src/types/state/StateOptions.type.ts), but is not present in the correct options type [state/StateSaveOptions.type.ts](https://github.com/dapr/js-sdk/blob/main/src/types/state/StateSaveOptions.type.ts)

Please feel free to assign this issue to yourself by commenting '/assign' on this and submit a PR. Thanks! :)
