### ISSUE TITLE
FEATURE PREVIEW: Add Actor State TTL support

### ISSUE THREAD

**Issue by JoshVanL** [dapr/js-sdk#482]
Add first class API support for Actor State TTL https://github.com/dapr/dapr/issues/5899

A dedicated function to Actor State should be created. Psudo code: `func (key string, value string, ttl duration)`. It should be made clear in the SDK documentation/comments that users should always use this function, unless they have specifically created some kind of Actor State clean up out of band of Dapr or don't have an issue with the Actor State store keep state and grow "forever".

Please see the [go-sdk](https://github.com/dapr/go-sdk/pull/383/files) for implementation reference. 

---

**UPDATE**: Due to the nature of the current implementation of write through caching of actor state and the unavailability of the real TTL expire time of state keys, SDKs will have an inconsistent view of the world when it has a cold cache and the state store has TTL keys. The TTL functionality has been put behind a feature gate in daprd. See https://github.com/dapr/dapr/pull/6400 for more details. This feature is expected to be moved to GA in 1.12.

**Comment by salmankhan-prs** [comment]
HI @shubham1172  for the above issue We need to create the separate function in `src/actors/runtime/ActorStateManager.ts`
right? If yes 

can you  go through these functions 

```javascript 
async setStateWithTTL(stateName: string, value: T, ttl: number): Promise<void> {
  const stateChangeTracker = this.getContextualStateTracker();

  if (stateChangeTracker.has(stateName)) {
    const stateMetadata = stateChangeTracker.get(stateName);

    if (!stateMetadata) {
      return;
    }

    stateMetadata.setValue(value);
    stateMetadata.setTTL(ttl);

    if (
      stateMetadata.getChangeKind() === StateChangeKind.NONE ||
      stateMetadata.getChangeKind() === StateChangeKind.REMOVE
    ) {
      stateMetadata.setChangeKind(StateChangeKind.UPDATE);
    }

    stateChangeTracker.set(stateName, stateMetadata);

    return;
  }

  const didExist = await this.actor
    .getStateProvider()
    .containsState(this.actor.getActorType(), this.actor.getActorId(), stateName);

  if (didExist) {
    stateChangeTracker.set(stateName, new StateMetadata(value, StateChangeKind.UPDATE, ttl));
  } else {
    stateChangeTracker.set(stateName, new StateMetadata(value, StateChangeKind.ADD, ttl));
  }
}
```

**Comment by salmankhan-prs** [comment]
@shubham1172  any update on this ?

**Comment by shubham1172** [comment]
Hi @salmankhan-prs, yes, you need to create this function in `ActorStateManager`. It LGTM from a high-level. Since `setStateWithTTL` is also a generalized version of `setState`, we can also explore reusing this implementation (e.g., if TTL < 0, don't set it. `setState` then calls `setStateWithTTL(name, val, -1)`.

**Comment by salmankhan-prs** [comment]
@shubham1172  you want  `setState` to call `setStateWithTTL`  internally 

```typescript
 async setState(stateName: string, value: T): Promise<void> {
  return await setStateWithTTL(name, val, -1).
 }
```

**Comment by shubham1172** [comment]
@salmankhan-prs yes, please feel free to create a PR, let me assign this issue to you.

**Comment by salmankhan-prs** [comment]
@shubham1172 I made PR.please verify it

**Comment by salmankhan-prs** [comment]
@shubham1172   can you help me to find out where I can write the test case for `setStateWithTTL `if It should be in `test/actors/DemoActorActivateImpl.ts` .can you also give a brief idea of how to write the test case It's somewhat difficult to me understand the testing approach of actors.

**Comment by shubham1172** [comment]
Taking this conversation to the pull request - @salmankhan-prs.

**Comment by JoshVanL** [comment]
@salmankhan-prs @shubham1172 I have update the issue description. For v1.11, This feature now requires the `ActorStateTTL` feature gate to be enabled in daprd.

**Comment by artursouza** [comment]
Can this be added in the next release?
