### ISSUE TITLE
Add test to validate package.json and package-lock.json has the same version

### ISSUE THREAD

**Issue by shubham1172** [dapr/js-sdk#505]
## Describe the proposal

While preparing for the release, we can miss bumping the version in package-lock.json if `npm install` was not run. Write a test to ensure that both the files have a consistent versioning.

**Comment by salmankhan-prs** [comment]
Hi @shubham1172  can you confirm that We need to validate  version  only  Js-SDK version or do we need to validate all other third-party library versions

**Comment by shubham1172** [comment]
Hi @salmankhan-prs this is specifically for JS-SDK.
