### ISSUE TITLE
Dev Ergonomics

### ISSUE THREAD

**Issue by RichiCoder1** [dapr/js-sdk#51]
## Describe the proposal
It looks like this repo has received minimal love, but I did want to propose a change that I think would make this lib much friendlier. The `protoc` generated javascript is....not great. From the pre-property `getXyz` and `setXyz`, to the bizzare naming, this lib is not very Javascript like.

I propose switching to something like [protobuf.js](https://github.com/protobufjs/protobuf.js#installation) which has a reasonably active implementation and generates much friendlier code by default.

**Comment by XavierGeerinck** [comment]
The library has been completely revamped to make it easier to develop with it! Go check out the new SDK calls and let me know what you think
