### ISSUE TITLE
Document That Users Can Self-Assign Issues

### ISSUE THREAD

**Issue by cicoyle** [dapr/js-sdk#525]
Please link to the [daprbot documentation](https://docs.dapr.io/contributing/daprbot/) inside the contributing.md file, so that users know what Github commands they can run in this repo. Based on the dapr-bot.yml they can run the [/assign to self assign issues and a few other commands](https://github.com/dapr/js-sdk/blob/main/.github/scripts/dapr_bot.js#L189) in this repo.

**Comment by sicoyle** [comment]
@owate There are a few more issues similar to this one for some of the other repos we'd love your help with! :)

https://github.com/dapr/cli/issues/1345
https://github.com/dapr/quickstarts/issues/924
https://github.com/dapr/python-sdk/issues/602
https://github.com/dapr/dotnet-sdk/issues/1149
https://github.com/dapr/java-sdk/issues/926

**Comment by owate** [comment]
Thanks @sicoyle. I will take a look at them too. I am trying to wet me feet first with a simple task and then consider a coding task.

**Comment by sicoyle** [comment]
> Thanks @sicoyle. I will take a look at them too. I am trying to wet me feet first with a simple task and then consider a coding task.

Amazing! Love that approach. Let me know if you need any help along the way 😁

**Comment by shubham1172** [comment]
@cicoyle, as a follow up we also need to update the daprbot reference to tell users if a command can be run by this SDK or not (and the few extra ones that are not a part of runtime/contrib).
