### ISSUE TITLE
Next.js DaprServer Module not found: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by majian159** [dapr/js-sdk#584]
## Actual Behavior

I'm attempting to start the DaprServer in instrumentation.ts in a Next.js project, but it's throwing an exception:
```console
○ Compiling /instrumentation ...
 ⨯ ./node_modules/.pnpm/@dapr+dapr@3.3.1/node_modules/@dapr/dapr/actors/ActorId.js:15:0
Module not found: Can't resolve 'crypto'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/@dapr+dapr@3.3.1/node_modules/@dapr/dapr/index.js
./src/instrumentation.ts
```
The code is as follows:
```typescript
import { CommunicationProtocolEnum, DaprServer } from "@dapr/dapr";

export async function register() {
  const server = new DaprServer({
    serverPort: "4000",
    communicationProtocol: CommunicationProtocolEnum.GRPC,
  });

  await server.start();
}
```

**Comment by shubham1172** [comment]
![image](https://github.com/dapr/js-sdk/assets/22132944/685919be-4b8e-44df-a340-5ea225f41375)

Does this help?

https://nextjs.org/docs/messages/module-not-found#the-module-youre-trying-to-import-uses-nodejs-specific-modules

**Comment by majian159** [comment]
This is not helpful; I am using the instrumentation.ts method with Next.js 14 to start the Dapr server.

This is a minimal reproduction repository: https://github.com/majian159/dapr-server-example

**Comment by shubham1172** [comment]
Thanks for sharing this @majian159, I am out this week but I/someone will check this soon.

**Comment by xAmast** [comment]
@shubham1172 My latest pull request replaces the crypto module with [crypto](https://developer.mozilla.org/zh-CN/docs/Web/API/crypto_property). This change will benefit all runtimes compliant with the WinterCG specification (including Next.js [Edge Runtime](https://nextjs.org/docs/app/api-reference/edge#crypto-apis)).
