### ISSUE TITLE
API Spec Proposal

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#62]
Hi All!

As discussed I would love to contribute an API spec proposal for the Dapr JS SDK :) It's a bit opiniated, but I hope it might lead to a discussion to see what can be improved.

Some of the key elements:
* Typescript
* Class based
* Extensibility

Usage example:

```javascript
// Initialize Express
const app = express();

// Initialize dapr service
const daprService = new Dapr("YOUR_URL", "YOUR_PORT");

// State Management
const res = await daprService.state.get("my-store-name", "key");
const res = await daprService.state.save("my-store-name", [{ key: "value" }]);

// Create binding (receive / send)
const res = await daprService.binding.send("my-queue", { hello: "world" });

daprService.binding.receive(app, "my-queue", bindingInput.bind(this));

async function bindingInput(data) {
    console.log("Receive Input");
    console.log(data);
}

// Create Pub Sub
const res = await daprService.pubsub.publish("my-pubsub", "my-topic", { hello: "world" });

daprService.pubsub.receive(app, "my-pubsub", "my-topic", bindingInput.bind(this));

async function bindingInput(data) {
    console.log("Receive Input");
    console.log(data);
}

// Invoke
const res = await daprService.invoke.invoke("app-id", "method-name", { hello: "world" });

await daprService.invoke.register(app, "my-endpoint", invokedEndpoint.bind(this));

async function invokedEndpoint(data) {
    console.log("Receive Input");
    console.log(data);
}
```

Some of the code I wrote for this can be found here: https://github.com/XavierGeerinck/PublicProjects/tree/master/JS/Dapr/AutoScalingHTTP/Gateway/src/API/dapr this has not been tested yet though... so some work is left to be done.

**Comment by krg7880** [comment]
Are there any plans to move forward with this proposal or something similar?

**Comment by XavierGeerinck** [comment]
I have been working on this in a separate repo: https://github.com/Roadwork/dapr-js-sdk I am now waiting for the original maintainers to discuss what to do :)

**Comment by XavierGeerinck** [comment]
@yaron2

**Comment by krg7880** [comment]
@XavierGeerinck That repo is what led me here as I was inclined to use it, except for the `Note: This library is not ready for production yet` disclaimer. It would be great to see some traction on it as it looks promising.

**Comment by artursouza** [comment]
@XavierGeerinck The library you started working on has potential. I would recommend working out of that fork and add Dapr maintainers to PRs into that fork - once the SDK is ready we can take a PR making it the official JS SDK for Dapr and make you a maintainer.

**Comment by XavierGeerinck** [comment]
Perfect, who should I add?

**Comment by artursouza** [comment]
Let's hear from other maintainers before agreeing on that.

**Comment by XavierGeerinck** [comment]
Adding a ping on this https://github.com/Roadwork/dapr-js-sdk has received more updates, most of the endpoints are there and tested. Transport for gRPC and HTTP have been added as well.

**Comment by XavierGeerinck** [comment]
Closing this
