### ISSUE TITLE
gRPC proxying and Dapr SDK

### ISSUE THREAD

**Issue by jsikorski** [dapr/js-sdk#626]
Hello,

My team and I have recently started with Dapr and Dapr JS SDK. It was enough for a simple application. However, we have noticed that it seems hard to use our own gRPC proto-based service with a server created using the SDK (DaprServer instance). For this reason, we went with Dapr proxying and grpc-js. This solution seems to be fine but we still want to use Dapr-specific features (e.g. pub/sub or actors).

We have tried different approaches:

1. Getting the proto file from Dapr SDK (from the npm package or GitHub) and adding a gRPC service to the server created using grpc-js. We wanted to use appcallback.proto to implement the service methods that are required when a sidecar requests the application, and dapr.proto for gRPC client to request the sidecar. However, we have found that these proto files aren't exported from Dapr JS SDK npm package.
2. Creating a server using Dapr SDK and adding our proto-based service to it. However, in this situation, we have to do some types casting in TypeScript (using 'as' keyword) which doesn't seem like a clean solution. We also need to start a server before adding a service (which seems a little strange).

Could you explain what the recommended approach is? We haven't found any sample that shows this situation. We also tried to find projects that use Dapr JS SDK and look at how they solve this issue. However, we couldn't find such projects using GitHub and npm dependencies.

If anything is unclear or needed, please let me know. Thanks in advance for your help.

**Comment by yaron2** [comment]
You can get the proto files from `dapr/dapr` (https://github.com/dapr/dapr/tree/master/dapr/proto), add them to your app and use the appcallback.proto from there.
