### ISSUE TITLE
What about providing a version 1.0 also for js-sdk

### ISSUE THREAD

**Issue by javageek79** [dapr/js-sdk#76]
## Ask your question here
As dapr now is on 1.0, what are your plans for the js-sdk. Are there any reasons not also releasing a final major version?

**Comment by artursouza** [comment]
The JS SDK is not feature complete like the Java SDK, .Net SDK or Python SDK. We need to build it out first and add proper testing before it can be called out as 1.0.

**Comment by XavierGeerinck** [comment]
Will be closing this since the JS SDK has received a ramp up in feature set. Thanks for reporting!
