### ISSUE TITLE
Code examples on how to use the Javascript SDK with each supported building block

### ISSUE THREAD

**Issue by greenie-msft** [dapr/js-sdk#82]
## Describe the proposal
Consider adding examples on how to use the JS SDK for each of the supported Building Blocks, e.g how to use the JS SDK for Service Invocation.

These examples will provide clarity on how to use the SDK. Additionally, we can raise visibility into the SDK by linking to the examples from each Building Block overview page.

**Comment by XavierGeerinck** [comment]
These can now be found in https://github.com/dapr/js-sdk/tree/master/examples

**Comment by amulyavarote** [comment]
@XavierGeerinck Are we missing any examples here? If not then, can we close this issue?

**Comment by XavierGeerinck** [comment]
We should maybe have a checklist where we can see which samples are missing and which aren't working anymore?

**Comment by amulyavarote** [comment]
We don't have example for actors in dapr.io. We have a separate issue tracking documentation for Actors. This is the issue for the same. #98
