### ISSUE TITLE
TypeScript example with incorrect grpc variable declaration / import

### ISSUE THREAD

**Issue by birapjr** [dapr/js-sdk#83]
## Expected Behavior

The declaration / import of the `grpc` in the [dapr js-sdk TypeScript example](https://github.com/dapr/js-sdk/blob/e30fd5c6971a72df84a1f73859c9ecb2cc262922/examples/typescript/app.ts#L7) come from the grpc library itself not from `dapr` import.

Correct declaration / import:
```
import grpc from 'grpc';
```

## Actual Behavior

The example extract the grpc from the `dapr module`
https://github.com/dapr/js-sdk/blob/e30fd5c6971a72df84a1f73859c9ecb2cc262922/examples/typescript/app.ts#L7

## Steps to Reproduce the Problem

When compiling the example the following error happens:
```
error TS2339: Property 'grpc' does not exist on type 'typeof import("js-sdk/node_modules/dapr-client/src/main")'.

27 var grpc = dapr.grpc;
                   ~~~~


Found 1 error.
```

**Comment by XavierGeerinck** [comment]
The API has been considerably changed, could you please check again once the latest version gets published to NPM? Closing this for now, feel free to re-open when issues arise!
