### ISSUE TITLE
Import errors when running examples

### ISSUE THREAD

**Issue by dolencd** [dapr/js-sdk#95]
## Expected Behavior
Examples should run if you follow the instructions.

## Actual Behavior
Examples don't run. The compiler gives errors about missing imports.

## Steps to Reproduce the Problem
Run the examples.

NodeJS doesn't find the library from the import of `@dapr/js-sdk`. This should be changed to `../../../../build` to reference the correct folder.

After changing this, more import errors occur, this time due to protos not having been compiled. An extra step should be added to the instructions, saying to run `./build.sh`, which compiles the protos.

**Comment by XavierGeerinck** [comment]
Examples have been updated and should run again, closing this. Let me know if you still encounter any issues :)
