### ISSUE TITLE
actors documentation

### ISSUE THREAD

**Issue by dpr-dev** [dapr/js-sdk#98]
hi everyone. does any documentation exist that describes how to use actors in the js sdk ?

**Comment by XavierGeerinck** [comment]
Hi there! The documentation is on it's way and will add the current actor implementation. We hope to get it published early next week!

**Comment by dpr-dev** [comment]
good news ! Thanks )

**Comment by amulyavarote** [comment]
Lets add any other actors related docs to this issue.

**Comment by amulyavarote** [comment]
@greenie-msft Can we get some help here?
